
- name: frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx server
      ansible.builtin.yum:
        name: nginx
        state: latest
         - name: remove directory
           ansible.builtin.file:
           path: /usr/share/nginx/html/
           state: absent
            - name: create directory
             ansible.builtin.file:
             path: /usr/share/nginx/html/
             state: directory
              - name: download and extract frontend
               ansible.builtin.unarchive:
                 src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
                 dest: /usr/share/nginx/html/
                 remote_src: yes
             - name: Copy roboshop configuration
               ansible.builtin.copy:
                 src: roboshop.conf
                 dest: /etc/nginx/default.d/roboshop.conf
             - name: start nginx service
               ansible.builtin.service:
                 name: nginx
                 state: restarted
                 enable: true


#echo -e "${color}extract frontend${nocolor}"
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip &>>/tmp/roboshop.log
#stat_check $?
#echo -e "${color}mupdating frontend roboshop configuration${nocolor}"
#cp /home/centos/roboshop-shell/roboshop.conf /etc/nginx/default.d/roboshop.conf
#stat_check $?
#echo -e "${color}starting nginx server${nocolor}"
#systemctl enable nginx &>>/tmp/roboshop.log
#systemctl restart nginx &>>/tmp/roboshop.log
#stat_check $?