
 #source common.sh
 #echo -e "${color} disable mysql default version${nocolor}"
 #yum module disable mysql -y &>>/tmp/roboshop.log
 #stat_check $?
 #echo -e "${color} copy mysql repo file${nocolor}"
 #cp /home/centos/roboshop-shell/mysql.repo /etc/yum.repos.d/mysql.repo &>>/tmp/roboshop.log
 #stat_check $?
 #echo -e "${color} install mysql community server ${nocolor}"
 #yum install mysql-community-server -y &>>/tmp/roboshop.log
 #stat_check $?
 #echo -e "${color} start mysql service${nocolor}"
 #systemctl enable mysqld &>>/tmp/roboshop.log
 #systemctl restart mysqld &>>/tmp/roboshop.log
 #stat_check $?
 #echo -e "${color} setup mysql password ${nocolor}"
 #mysql_secure_installation --set-root-pass $1 &>>/tmp/roboshop.log
 #stat_check $?

 - name: disable mysql default version
   ansible.builtin.shell: yum module disable mysql -y

 - name: copy mysql repo file
   ansible.builtin.copy:
     src: roboshop-shell/mysql.repo
     dest: /etc/yum.repos.d/mysql.repo

 - name: Install mysql community server
   ansible.builtin.yum:
     name: mysql-community-server
     state: installed

 - name: start mysql service
   ansible.builtin.systemd:
     name: mysqld
     state: restarted
     enabled: yes
 - name: setup mysql password
   ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

