
 - name: Install maven
   ansible.builtin.yum:
     name: maven
     state: installed

 - name:  app pre_requisite
   ansible.builtin.import_tasks:
     file: app_pre_setup.yml

 - name: Download maven dependencies
   ansible.builtin.shell: mvn clean package; mv target/{{ component }}-1.0.jar {{ component }}.jar
   args:
      chdir: /app

 - name: mysql schema setup
   ansible.builtin.import_tasks:
     file: mysql_schema_setup.yml

 - name: Systemd_setup
   ansible.builtin.import_tasks:
     file: systemd_setup.yml