

 - name: Install Mysql Client
   ansible.builtin.yum:
     name: mysql
     status: installed

 - name: load Schema
   ansible.builtin.shell: mysql -h mysql-dev.devops73.in -uroot -pRoboShop@1 </app/schema/{{ component }}.sql


