 - name: configuration nodejs repos
   ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
 - name: Install Nodejs
   ansible.builtin.yum:
     name: nodejs
     state: Installed





 #app_pre_setup

 #systemd_setup

 #echo -e "${color} install nodejs dependencies ${nocolor}"
 #npm install &>>${log_file}
 #stat_check $?
